trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: terraformVersion
  value: '1.5.0'

stages:
- stage: Validate
  jobs:
  - job: ValidateJob
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '$(terraformVersion)'
    - script: terraform init
    - script: terraform validate

- stage: Deploy
  dependsOn: Validate
  jobs:
  - job: DeployJob
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '$(terraformVersion)'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'kanna'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account show
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan